### ISSUE TITLE
Demande de développement "Azimut"  

### ISSUE THREAD

**Issue by DylanRecordon** [opengisch/signalo#101]
Bonjour,

Lors de la saisie de la signalisation, il s'agit de renseigner un attribut "azimut" pour l'orientation de la signalisation. Actuellement, cet attribut est saisi "à l'œil". Serait-il possible de développer un outil qui permettrait d'orienter le signal directement dans la représentation graphique ? Cela éviterait de procéder par tâtonnement et ainsi, éviter de nombreux clics.

Avec mes meilleures salutations
Dylan

**Comment by 3nids** [comment]
oui c'est possible, probablement avec QML, comme ça cela serait dispo sur QField et QGIS Desktop.

**Comment by 3nids** [comment]
duplicate #108
