### ISSUE TITLE
OSR 4.27 et 4.29 début de localité avec nom de localité sur 2 et 3 lignes

### ISSUE THREAD

**Issue by DylanRecordon** [opengisch/signalo#103]
Bonjour,

Lors de la saisie des signaux OSR 4.27 et 4.29, début de localité nous rencontrons un bug; si la localité est écrite sur 2 ou 3 lignes, la représentation sur la carte Signalo ne prend pas en compte la 2ème ni la 3ème ligne;

![image](https://github.com/opengisch/signalo/assets/134506740/83ef359d-96e9-41d4-af5e-32dac3b7b58b)

![image](https://github.com/opengisch/signalo/assets/134506740/76ee970d-0709-4d9a-aa0a-3f564b2e43f2)

Vous constaterez que le texte "Commune de la Val-de-Ruz" ne s'affiche pas.
 
Merci de corriger ce bug. Pour information, nous constatons que les signaux OSR 4.28 et 4.30, fin de localité fonctionnement.

Avec mes meilleures salutations.
Dylan

**Comment by 3nids** [comment]
on va créer un nouveau signal avec 2 lignes
