### ISSUE TITLE
Signalisation "balisage"

### ISSUE THREAD

**Issue by DylanRecordon** [opengisch/signalo#104]
Bonjour,

Signalo dispose d'un type de signal "balisage";

![image](https://github.com/opengisch/signalo/assets/134506740/1f66428f-aa55-42ef-9a7f-8703d2dab366)

Avec cet attribut, le rendu sur la carte se fait ainsi;

![image](https://github.com/opengisch/signalo/assets/134506740/369d02ea-e91a-498b-b646-5acf2550b14c)

Il faudrait développer différents types de signal,  spécifiques au balisage;

- **Borne d'îlots :**
 En situation: 
 ![image](https://github.com/opengisch/signalo/assets/134506740/02e288ab-18b8-4ce9-bf0e-dc8bdd37b0c7)

 Dans signalo: 
 ![image](https://github.com/opengisch/signalo/assets/134506740/369d02ea-e91a-498b-b646-5acf2550b14c)

Idéalement proposer une variant noir / blanc et une variante jaune / noir

- **Flèche de balisage :** 
En situation:
![image](https://github.com/opengisch/signalo/assets/134506740/2855856d-7ead-4686-b7f6-7b784018852e)

=> inexistant dans Signalo, voici la représentation selon la norme:
 
![image](https://github.com/opengisch/signalo/assets/134506740/46f35205-b343-4c0f-8b0a-fad65a86e3a6)

- **Flèche de balisage multiple :** 
En situation:
![image](https://github.com/opengisch/signalo/assets/134506740/73b63d1b-55e1-4699-8ee7-901ef6d932a4)

=> inexistant dans Signalo, voici la représentation selon la norme:
![image](https://github.com/opengisch/signalo/assets/134506740/aa821297-28a4-44d5-bc70-e8049cd73b4e)

Egalement à créer en séparateur de trafic

![image](https://github.com/opengisch/signalo/assets/134506740/9766788c-e439-41e8-a14a-3f92fa3a97cb)

- **Balise de guidage :**
En situation:
![image](https://github.com/opengisch/signalo/assets/134506740/f8ae298b-0d49-4c86-bf86-6fcc68f3aee5)

=> inexistant dans Signalo, voici la représentation selon la norme:
![image](https://github.com/opengisch/signalo/assets/134506740/f4236fee-7e62-4d60-bcbc-968ae5b945af)

A créer en gauche / milieu / droite 

- Bande de balisage:

=> Inexistant dans Signalo, voici la représentation selon la norme:
![image](https://github.com/opengisch/signalo/assets/134506740/11f58a21-db23-491e-b89b-999d91a80e58)

Avec mes meilleures salutations.
Dylan

**Comment by spch-GL** [comment]
nous proposons de nommer ces panneaux de balisage selon la norme VSS 40822 « Dispositifs de balisage » ;

-	Flèche de balisage simple ;
![image](https://github.com/opengisch/signalo/assets/26377323/1b403268-75f3-4ca9-be3c-b7f3ad53d2a2)

-	Flèche de balisage multiple ;
 ![image](https://github.com/opengisch/signalo/assets/26377323/73743348-29dd-43cc-9489-d71676ad8c02)


-	Séparateur de trafic de type B ;
 ![image](https://github.com/opengisch/signalo/assets/26377323/d7e4f8f7-7077-45e8-b0eb-90298019b393)


-	Balise de guidage gauche ;
 ![image](https://github.com/opengisch/signalo/assets/26377323/e808e3fc-2f7d-4be5-882f-4aa050ebc25c)


-	Balise de guidage milieu ;
 ![image](https://github.com/opengisch/signalo/assets/26377323/44b6158f-3c99-41cc-a31a-ccbbc9072a1c)


-	Balise de guidage droit ;
 ![image](https://github.com/opengisch/signalo/assets/26377323/c57f3886-d682-4a6c-ab1a-a05b87659556)


-	Bande de balisage ; 
 ![image](https://github.com/opengisch/signalo/assets/26377323/f6008c7b-6611-4b07-8ba3-d1bbc6c6f815)

**Comment by spch-GL** [comment]
Et une Borne d'îlots en PU:
![BornePU](https://github.com/opengisch/signalo/assets/26377323/1597b817-8284-43d4-92d1-c0be72e46144)
[BornePU.zip](https://github.com/opengisch/signalo/files/15485522/BornePU.zip)

**Comment by itsakifa** [comment]
@spch-GL: concernant les bandes de balisages directionnelles. 

Est-ce que cet exemple correspond à la version gauche ou droite?

![image](https://github.com/opengisch/signalo/assets/4679915/13e14e11-4b93-46f0-b173-37365f20eb87)

**Comment by spch-GL** [comment]
@itsakifa: Cet exemple correspond à la gauche, merci
