### ISSUE TITLE
Signalisation multiple placée sur le même niveau

### ISSUE THREAD

**Issue by DylanRecordon** [opengisch/signalo#105]
Bonjour,

Lors de la saisie des cadres, il s'agit de leur attribuer un ordre. Comment procéder pour placer deux signaux à même niveau et que cela soit représenté sur la carte ainsi ?

Voici la situation :

![image](https://github.com/opengisch/signalo/assets/134506740/bf095ad6-a93b-4262-a43c-2fd3951858e4)

Avec mes meilleures salutations
Dylan

**Comment by 3nids** [comment]
On va se pencher là-dessus
