### ISSUE TITLE
Problème performance

### ISSUE THREAD

**Issue by m-vaucher** [opengisch/signalo#107]
Bonjour,

Nous avons migré la signalisation de police sur le canton de Neuchâtel. Cela représente un peu moins de 9'000 signaux.
Pour commencer nos travaux de reprise des données, nous avons démarré par quelques axes de routes et la performance à l'ouverture des différents formulaires imbriqués ne posait aucun problème. Avec le solde des données de police, qui ne représentent pas un jeu de données spécialement volumineux comme Opencomptage par ex nous avons des temps de latence à l'ouverture du signal depuis le cadre de 7 - 8 secondes. Et cela va augmenter avec la migration de la signalisation directionnelle. Le p

Serait-il possible d'améliorer la performance ? Nous avons en outre remarqué qu'il n'y avait aucun index sur les tables.

![image](https://github.com/opengisch/signalo/assets/32130631/28e8d7f5-36eb-4d60-b7e3-2af732ce8e2b)
![image](https://github.com/opengisch/signalo/assets/32130631/a0a467be-adbc-4bc9-9158-7c2be471c4fc)

Merci d'avance et bonne journée
Meilleures salutations
Marc Vaucher

**Comment by 3nids** [comment]
pouvez-vous nous transmettre un dump des données afin de tester?

**Comment by 3nids** [comment]
@m-vaucher est-ce toujours d'actualité? est-ce possible de nous transmettre un dump ou souhaitez-vous attendre le refactoring (je ne pense pas que cela va affecter la rapidité, mais en tout cas pas dans le bon sens)

**Comment by spch-GL** [comment]
Voici enfin le DUMP...
[signalo_prod.dmp](https://github.com/opengisch/signalo/files/13051991/signalo_prod.dmp)

**Comment by spch-GL** [comment]
Après 2 tests en internes, sur 2 PC différents, en passant à la 3.28.11 (au lieu de la 3.22.nn) le temps de latence n'est plus qu'à ~2 secondes et ce n'est plus trop problématique pour travailler.
