### ISSUE TITLE
Gestion geo-facilitée des azimut

### ISSUE THREAD

**Issue by ponceta** [opengisch/signalo#108]
Comme proposé dans une précédente session, j'imagine qu'utiliser un élément linéaire pour représenter les azimut permettrait de manière assez simple et intuitive de modifier l'orientation d'un azimut par rapport au point du support :

![image](https://github.com/opengisch/signalo/assets/8614223/3f24ce81-6b47-4329-8c29-d5f448cf1fb7)

La ligne pourrait être créé semi automatiquement en renseignant la valeur d'azimut. La modification de l'azimut pourrait ensuite être mise à jour en déplaçant le point de fin autour du support.

- [ ] Un manque actuel côté QGIS, la possibilité de créer une valeur par défaut de géométrie pour une nouvelle entité. (contournable à priori par une action python)

C'est une approche déjà utilisée au sein des géoportails romands pour faciliter la saisie de l'orientation des symboles 

![image](https://github.com/opengisch/signalo/assets/8614223/01f81cd9-3d82-4d87-b66e-2e9f5f7aeed6)

La symbologie montrée ci-dessus est basée sur le générateur de géométrie, aujourd'hui ceci ne permet pas l'édition.

```
-- geom_to_wkt( $geometry)
make_line(
	$geometry,
	project(
		$geometry,
		10.0,
		array_first((
			relation_aggregate( 
				'support_azimut',
				'array_agg', 
				 radians( azimut))))))
```

**Autre améliorations potentielles de QGIS utiles pour ce genre d'interactions :**
- [ ] Créer une géométrie sur la base d'un champ virtuel (calculé)
- [ ] Créer une symbologie pour une telle couche (sur la base du champ virtuel ou du générateur de géométrie, possible sur toute couche avec une géométrie initialement définie)

**Comment by 3nids** [comment]
faire une vue pour les azimuth avec une longueur de ligne basée une longueur écran donnée à une échelle donnée.
trigger pour les modifications.

solution à préciser.
