### ISSUE TITLE
Projet qgs - Ajout du fond orthophoto swissimage

### ISSUE THREAD

**Issue by ponceta** [opengisch/signalo#109]
- [x] Créer un groupe **Fonds de plans** mutuellement exclusif

![image](https://github.com/opengisch/signalo/assets/8614223/bebaeac7-52ce-4b76-812c-a9f663677dc2)

- [x] Ajouter l'orthomosaïque swissimage

![image](https://github.com/opengisch/signalo/assets/8614223/d21c8d12-159d-4498-95cd-dcc4fa0f87aa)

**Comment by itsakifa** [comment]
included here:
https://github.com/opengisch/signalo/commit/b8ca26501f691ddc7cf7fc43ae04889b49826e6e
