### ISSUE TITLE
Photos many-to-many

### ISSUE THREAD

**Issue by gildas-allaz** [opengisch/signalo#119]
Bonjour,

Partant de l'expérience chaux-de-fonnière pour d'autres bases de données, j'aimerais proposer une amélioration de la gestion des photographies permettant de répondre aux besoins suivants :

1. Un fichier image est consulté soit via un réseau informatique local, soit par le web. Les chemins d'accès complets pour ces deux configurations étant différents, l'enregistrement d'un nom de fichier peut se faire à l'aide de 5 attributs permettant de générer automatiquement (par QGIS ou PostgreSQL) toutes les combinaisons possibles :

    o	chemin du dossier local (avec définition de valeur par défaut)
    o	chemin du dossier web (avec définition de valeur par défaut)
    o	nom du fichier seul
    o	chemin d'accès complet local = dossier local + nom fichier
    o	chemin d'accès complet web = dossier web + nom fichier

2. Le choix de relier une photographie prise sur le terrain à l'un ou l'autre des objets (support, azimut, cadre, signal) n'est pas forcément évident pour un opérateur sur le terrain.

3. Gestion de plusieurs photographies pour un même objet (y compris à des époques différentes) ou d'une seule photographie pour plusieurs objets.

La création d'une seule table indépendante de photographies, composée a minima des 5 attributs précités, reliée à chacune des tables des objets (support, azimut, cadre, signal) par des relations _many-to-many_ répond sans difficulté à ce besoin.

Voici en pièce jointe un exemple de script de mise en place de cette solution :
[tbl_photo_rel_objects.sql.txt](https://github.com/opengisch/signalo/files/12727967/tbl_photo_rel_objects.sql.txt)

Avec mes cordiales salutations.

Gildas Allaz
Secteur Géomatique
La Chaux-de-Fonds

**Comment by itsakifa** [comment]
Bonjour @gildas-allaz,

J'ai transféré cette question sur la plateforme de support. Lors d'un des derniers ateliers, la gestion des photos a été discuté et il a été décidé d'avoir 2 champs de photo sur la couche support. Il est cependant possible que nous créons un script par-dessus le projet QGIS, qui ajoute une table photos et adapte le formulaire d'attributs en fonction des besoins de la Chaux-de-Fonds - je vais spécifier plus sur la plateforme de support. 

Meilleures salutations
Isabel
