### ISSUE TITLE
Release version not updated in project name (after v0.6.2)

### ISSUE THREAD

**Issue by itsakifa** [opengisch/signalo#127]
Check if project name has to be reset to signalo_demo.qgs to fit project title automatically to release version.

Should be 0.6.3 
![image](https://github.com/opengisch/signalo/assets/4679915/7ec841d2-c4ef-4bb2-bf83-cab494266060)

+ Add a test for version number when building release package

**Comment by 3nids** [comment]
solved in 1.0.0
