### ISSUE TITLE
Corriger scripts sql pour mise à jour incrémentale de la BD

### ISSUE THREAD

**Issue by itsakifa** [opengisch/signalo#128]
Il semble exister une différence entre une installation complètement nouvelle de la version actuelle et une base de données mise à jour de manière incrémentale à chaque release. 3 triggers ont été enlevés dans une nouvelle version mais sont toujours visibles dans la BD mise à jour incrémentalement. 

C’est un oubli dans les scripts de mise à jour.

**Comment by 3nids** [comment]
solved in 1.0.0
