### ISSUE TITLE
Formulaire QField - liste signaux officiels

### ISSUE THREAD

**Issue by gildas-allaz** [opengisch/signalo#132]
Bonjour,

Dans la version 0.6.3, la liste des signaux officiels OSR ne s'affiche pas dans QField.

Je constate que la relation entre le signal et la liste de valeurs (fk_official_sign) était définie ainsi dans la version 0.6.0 :
![image](https://github.com/opengisch/signalo/assets/70746346/0bed2ae8-9901-4b51-9427-3a3e47fc9864)
**"id" || ' ' ||"value_fr"**
ce qui ne posait aucun problème d'affichage dans QField.

Cette relation est définie ainsi dans la version 0.6.3 :
![image](https://github.com/opengisch/signalo/assets/70746346/5a115ec7-11cd-436e-973e-a62f7a0bacf2)
**"id" || ' ' || attribute('value_' || @qgis_locale )**

Sans connaître l'impacte de cette différence, j'observe que le problème de disponibilité de la liste de valeurs dépend de cette configuration.

Pourriez-vous adapter cette définition de relation de manière à ce que la liste soit disponible sur QField ?

Avec mes cordiales salutations.

Gildas Allaz

**Comment by itsakifa** [comment]
Bonjour,

L'expression a été changé pour permettre l'utilisation du projet dans plusieurs langues. La variable @qgis_locale n'existe pas encore dans QField, c'est pourquoi l'expression ne marche pas dans l'application mobile. 
Nous l'avons signalé dans le repo de QField (https://github.com/opengisch/QField/issues/4795) et allons mettre en place un workaround pour refaire marcher l'affichage de la liste.

**Comment by itsakifa** [comment]
https://github.com/opengisch/QField/issues/4795

**Comment by itsakifa** [comment]
@gildas-allaz il y a effectivement eu un bug dans QField lié à la variable qgis_locale qui comprend l'information de la lange de l'interface. Ce problème sera réglé avec une prochaine version de QField
voir aussi : https://github.com/opengisch/QField/pull/4965

**Comment by itsakifa** [comment]
La nouvelle version incluant la solution à ce bug sortira fin février
