### ISSUE TITLE
User-defined signs and mirror representation

### ISSUE THREAD

**Issue by spch-GL** [opengisch/signalo#133]
here is what I see on the map view: 
![image](https://github.com/opengisch/signalo/assets/26377323/59191ecf-8b02-48cb-b650-a8eb33178f56)

Between the support and the right turn (Azimut=0) we should see a user-defined sign : 
![image](https://github.com/opengisch/signalo/assets/26377323/219db5bd-8bfc-4117-9a20-21bd51835ca6)

Between the support and the left turn (Azimut=180) is a rectangular mirror `whith red and white border`. If we modify it to be circular, nothing changes on the view.

**Comment by 3nids** [comment]
mirrors have been fixed 

I cannot reproduce the issue with user defined image.
