### ISSUE TITLE
OSR 4.77 - représentation incorrecte

### ISSUE THREAD

**Issue by itsakifa** [opengisch/signalo#147]
La représentation OSR 4.77 n’est pas correcte, il s’agit de créer les variantes suivantes ;

![image](https://github.com/opengisch/signalo/assets/4679915/9248bf16-169a-426a-9270-0a6aad9123a2)
(faux à supprimer)

à créer
4.77.1
![image](https://github.com/opengisch/signalo/assets/4679915/370c34bc-019d-4358-a27a-4c6497f69da3)

4.77.2
![image](https://github.com/opengisch/signalo/assets/4679915/0ee1cc40-3c18-4571-af75-bf50d6a6b52c)

4.77.3
![image](https://github.com/opengisch/signalo/assets/4679915/cbce988b-278a-4157-937e-fe8475a23729)

4.77.4
![image](https://github.com/opengisch/signalo/assets/4679915/09c5b479-bdd9-43db-8010-115c7f9c26fd)

4.77.5
![image](https://github.com/opengisch/signalo/assets/4679915/c089ad1d-7e1b-46d7-8d14-583292ea07e3)

4.77.6
![image](https://github.com/opengisch/signalo/assets/4679915/9a8abb22-00c3-41c5-8522-156ec90b7937)

4.77.7
![image](https://github.com/opengisch/signalo/assets/4679915/245371be-9ccd-460a-8840-dc9ef6a849c2)

4.77.8
![image](https://github.com/opengisch/signalo/assets/4679915/8ac73788-182e-4be6-8eee-13d9111b94db)

4.77.9
![image](https://github.com/opengisch/signalo/assets/4679915/63b62477-7c23-4112-bc97-3a148bd1c162)

4.77.10
![image](https://github.com/opengisch/signalo/assets/4679915/72a03a23-0a7d-4ec6-9c67-5bca420e0b40)

4.77.11
![image](https://github.com/opengisch/signalo/assets/4679915/e17f83f4-996a-44b9-96e8-4bb7b00a722c)

4.77.11a et 4.77.10a (dynamique)
![image](https://github.com/opengisch/signalo/assets/4679915/2dac8ce6-df5b-4078-8549-6b48338a921b)

o   4.77.12
![image](https://github.com/opengisch/signalo/assets/4679915/cb147550-8663-4c5d-8092-b7e45b7d5381)

o   4.77.13
![image](https://github.com/opengisch/signalo/assets/4679915/2f3a5168-0003-417b-8122-eb5b24418074)

o   4.77.14
![image](https://github.com/opengisch/signalo/assets/4679915/143f585a-98e4-4625-90f1-27b6d1f5f459)

o   4.77.15
![image](https://github.com/opengisch/signalo/assets/4679915/1f90aad2-13af-47bf-8fff-f25354c2c432)

o   4.77.16
![image](https://github.com/opengisch/signalo/assets/4679915/1de7b8ea-314f-477d-99fe-ef9eb54e5a7d)

o   4.77.17
![image](https://github.com/opengisch/signalo/assets/4679915/cb8e351b-1f03-4755-8601-34648f711248)

o   4.77.18
![image](https://github.com/opengisch/signalo/assets/4679915/4a73f192-2d66-4af7-be47-adbbf78c0874)

o   4.77.19 
![image](https://github.com/opengisch/signalo/assets/4679915/0d8ed88c-1845-47f7-a683-36dcff25c1a7)

o   4.77.20
![image](https://github.com/opengisch/signalo/assets/4679915/a23af216-7918-4625-99cd-e5a9de302943)

o   4.77.21
![image](https://github.com/opengisch/signalo/assets/4679915/a5f58110-3be5-4322-a800-bd65c42d1f62)

o   4.77.22
![image](https://github.com/opengisch/signalo/assets/4679915/e6895dfd-d711-40e1-a723-ebb48b258341)

o   4.77.23
![image](https://github.com/opengisch/signalo/assets/4679915/cf7b1ede-63b0-4074-9e08-8d6b12eb0587)

o   4.77.24
![image](https://github.com/opengisch/signalo/assets/4679915/7cbaf518-34d2-4b15-b971-4c1cf215641a)

o   4.77.26 + 4.77.26a (flèche gauche vers droite)
![image](https://github.com/opengisch/signalo/assets/4679915/b63dba4d-35f2-4b11-8e47-6494a2350af8)

o   4.77.27
![image](https://github.com/opengisch/signalo/assets/4679915/2deeaead-d755-4c33-9717-934855eaa734)

o   4.77.28
![image](https://github.com/opengisch/signalo/assets/4679915/0aede49a-d4a2-44ab-b4f5-32239e6d2368)

o   4.77.29 
![image](https://github.com/opengisch/signalo/assets/4679915/2ef2919f-fe45-4033-bf4e-5bd4fff6a07b)

o   4.77.30 (dynamique) 
![image](https://github.com/opengisch/signalo/assets/4679915/2cb79033-9392-412f-83d9-16d679d83d45)

**Comment by 3nids** [comment]
serait-il possible d'avoir toutes les images au format vectoriel?

**Comment by itsakifa** [comment]
Il y a un problème avec la 4.77.1 qui selon l'OSR est 
<img width="863" alt="image" src="https://github.com/opengisch/signalo/assets/4679915/8fe8aaf6-73a2-4947-9171-138df066147d">
Ainsi que la 4.77.2 
<img width="846" alt="image" src="https://github.com/opengisch/signalo/assets/4679915/5eea76a3-cc75-4c5f-80bc-553297b927b1">

Ces deux identifiants sont donc déjà pris.

D'où vient la nomenclature des id ci-dessus ? 
<img width="112" alt="image" src="https://github.com/opengisch/signalo/assets/4679915/17ec1893-7ff2-436a-baca-1d091d26b330">

**Comment by FredDucry** [comment]
Salut Isabel,

Je ne sais pas d’où provienne ces indications.

Pour ma part, je travaille avec la brochure du TCS et ces signaux sont déjà attribués :

***@***.***

Un bel après-midi à toi.


Frédéric Ducry · Spécialiste SIG
***@***.***
Service de la mobilité et de l’aménagement des espaces publics
rue du Port-Franc 18 • CP 5354 - 1001 Lausanne • Tél. +41 21 315 38 09
Géolocalisez-moi sur Google Maps !

[gmaps_link03b.png]<http://maps.google.ch/maps?f=q&source=s_q&hl=fr&geocode=&q=port-franc+18,+lausanne&aq=&sll=46.521902,6.625914&sspn=0.00065,0.001206&ie=UTF8&hq=&hnear=Rue+du+Port-Franc+18,+1003+Lausanne,+Vaud&ll=46.521548,6.626194&spn=0.005197,0.009645&z=17> ***@***.*** <http://www.linkedin.com/in/fducry>  [upload icon] <https://fex.lausanne.ch/filedrop/~ljk9Yg>  ***@***.*** <tel:+41213153809>  ***@***.*** <tel:+41797148402>

De : Isabel Kiefer ***@***.***
Envoyé : lundi, 11 mars 2024 14:22
À : opengisch/signalo ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [opengisch/signalo] OSR 4.77 - représentation incorrecte (Issue #147)


Il y a un problème avec la 4.77.1 qui selon l'OSR est
image.png (view on web)<https://github.com/opengisch/signalo/assets/4679915/8fe8aaf6-73a2-4947-9171-138df066147d>
Ainsi que la 4.77.2
image.png (view on web)<https://github.com/opengisch/signalo/assets/4679915/5eea76a3-cc75-4c5f-80bc-553297b927b1>

Ces deux identifiants sont donc déjà pris.

D'où vient la nomenclature des id ci-dessus ?
image.png (view on web)<https://github.com/opengisch/signalo/assets/4679915/17ec1893-7ff2-436a-baca-1d091d26b330>
