### ISSUE TITLE
azimut value changed

### ISSUE THREAD

**Issue by 3nids** [opengisch/signalo#162]
Since 1.0.0-RC1, the values of azimuts might be different

![image](https://github.com/opengisch/signalo/assets/127259/111a6c23-186b-4d01-a414-cedfbc9ddef4)

180° means pointing to the north (text is reversed), 0° means pointing to the south.
should this be switched back?

**Comment by spch-GL** [comment]
Par définition l'azimut est défini par rapport au nord : Azimut=0 -> pointe au nord

**Comment by spch-GL** [comment]
Si il y a une bonne raison pour changer le sens de l'angle, alors il ne faut plus l'appeler azimut
