### ISSUE TITLE
type de support: NULL

### ISSUE THREAD

**Issue by spch-GL** [opengisch/signalo#163]
Mes données de test ont le type de support NULL et la borne d'ilot s'affiche:
![image](https://github.com/opengisch/signalo/assets/26377323/6dc4617a-6f10-4e25-b292-58abc54f2e1b)

Après édition de l'azimut (pour voir si le tronquage changeait, mais cela n'a pas été le cas), le type de support a changé pour `inconnu` et la borne ne s'affiche plus !
![image](https://github.com/opengisch/signalo/assets/26377323/64d0d22c-42f4-42b1-92ca-ae2fceb8b5ef)

Faut-il gérer ces NULL dans le projet ou corriger les données ?

**Comment by 3nids** [comment]
si tu installes les données démo, cela ne devrait plus être le cas.

je corrige le problème dans tous les cas dans le projet.
