### ISSUE TITLE
Signalisation directionnelle: touristique

### ISSUE THREAD

**Issue by spch-GL** [opengisch/signalo#168]
Elle devrait avoir les mêmes dimensions et les mêmes caractéristiques dynamiques que les autres. 
Exemple de rendu actuel:
![image](https://github.com/opengisch/signalo/assets/26377323/4c94c405-261a-4f11-a727-2951dba4f702)

**Comment by 3nids** [comment]
reprendre le signal directionnel et changer la couleur pour faire le touristique
