### ISSUE TITLE
décalage verso

### ISSUE THREAD

**Issue by 3nids** [opengisch/signalo#176]
Avec ces panneaux introduits via la RC6, le décalage des `verso `n'est toujours pas corrigé (déjà signalé en RC5, le 19 décembre):
![image](https://github.com/opengisch/signalo/assets/26377323/32a0d5b1-7992-4030-84b7-adf064ab5667)

AZ : Azimut
Dy : Décalage Y
RV : Recto-Verso

Signaux verts: 1 signal Recto-Verso dans le cadre 1 de l'azimut 0
Signaux bleus : 2 signaux,1 Recto + 1 Verso, dans le cadre 1 de l'azimut 120
Signaux blancs : 2 signaux,1 Recto dans le cadre 1 et 1 Verso dans le cadre 2, le tout dans l'azimut 240

from https://github.com/opengisch/signalo/commit/e69099b1305869c343d1d63cad904ff8ea55d728#commitcomment-138122362

**Comment by 3nids** [comment]
je doute un peu sur la bonne façon de corriger ce bug, en faisant des tests, je ne suis pas sûr qu'il faille simplement reporter le décalage sur le verso

pour info, si l'azimut+180 correspond à une entrée dans la table azimut, les signaux sont tous groupés, du coup, dans ce cas, l'azimut ne serait pas reporté mais on prendrait le décalage de l'entrée azimut trouvée.

j'identifie ces solutions:
1. ne rien faire
2. reporter l'azimut du verso (sauf si groupement avec un autre azimut)
3. avoir une option (reporter ou non le décalage)
4. ajouter des attributs décalage verso

j'ai l'impression que c'est uniquement avec 4. que l'on pourra correctement solutionner le problème.

ping @spch-GL

**Comment by spch-GL** [comment]
> pour info, si l'azimut+180 correspond à une entrée dans la table azimut, les signaux sont tous groupés, du coup, dans ce cas, l'azimut ne serait pas reporté mais on prendrait le décalage de l'entrée azimut trouvée.

Désolé, mais je ne comprends pas ce que tu essaies de dire

**Comment by 3nids** [comment]
si tu as un azimut A1 à 90° avec un signal X recto-verso et un autre azimut A2 à 270° (=A1+180) avec un signal Y et Z, alors à 270°, tu auras un bloc Y, Z puis X. C'est le décalage de l'azimuth A2 qui est pris en compte (le décalage de A1 n'interviendra pas car X se met à la suite des signaux de A2)

**Comment by 3nids** [comment]
solution 4 retenue
