### ISSUE TITLE
Décalage de la balise supportant des signaux ancrés à gauche et/ou à droite

### ISSUE THREAD

**Issue by spch-GL** [opengisch/signalo#186]
Avec le projet `signalo-1.0.0-RC6-project\project\signalo_dev.qgs` (original, daté du 30.01.2024 19:12) la balise n'est pas décalée dans le sens de l'azimut
Voici une copie d'écran de la vue carte:
![image](https://github.com/opengisch/signalo/assets/26377323/641bd501-3448-4454-bb8d-7cfb24b2cd48)
Voici les données introduites:
[Signalo_balise.csv](https://github.com/opengisch/signalo/files/14277278/Signalo_balise.csv)

Puisque vous ne reproduisez pas ce souci
![image](https://github.com/opengisch/signalo/assets/26377323/08f014f6-7f00-417e-8713-2c6a5314560c)

provient-il :
1. de mon environnement (Windows 10, QGIS 3.28.15 ?) ?
2. de ma BD (souci de migration ?) ?
3. du projet ?
4. de l'image de la balise ?
5. d'autre chose... ?

**Comment by 3nids** [comment]
Il n'y a plus besoin d'ajouter un signal de type balise, tu peux le supprimer.
C'est dans le type de support, tu dois mettre `borne d'ilôt`

**Comment by spch-GL** [comment]
Merci, cela fonctionne
Et c'est effectivement plus logique comme cela
