### ISSUE TITLE
website DE

### ISSUE THREAD

**Issue by itsakifa** [opengisch/signalo#187]
Some small bugs should be resolved
- [x] Logo is missing on de version
- [ ] Logo, title and text on starting page are not aligned on the left (de and fr)
- [x] tab names in mobile are not correct yet (fr)
- [x] Titles and menu names are not translated yet

**Comment by 3nids** [comment]
what do you mean for the tab names in mobile? they are fine here.

**Comment by itsakifa** [comment]
@3nids - alignment on landing page, is that something that can be changed?

**Comment by 3nids** [comment]
not 100% sure, but the text is from here https://github.com/opengisch/signalo/blob/5c0a655790fae1c83fce2a4d68c22a3f2b6682bd/website/theme_overrides/home.html#L16

looking at the CSS, maybe you can try to modify: https://github.com/opengisch/signalo/blob/5c0a655790fae1c83fce2a4d68c22a3f2b6682bd/website/theme_overrides/assets/stylesheets/main.3ca7bbfe.min.css#L172
