### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by 3nids** [opengisch/signalo#199]
* [x] duplication objets
* [x] création de signaux dynamiques
* [ ] respect normes OSR + DSS

**Comment by 3nids** [comment]
quelques remarques sur la version en cours de dev:

* renommer participer en contribuer?
* harmoniser les titres de chaque page: s'assurer qu'elle commence par le titre et que les sous chapitres suivant aient une police plus petite (la page installation est ok, la page concepts non)
* la MAJ du modèle de données est présent 2 fois, l'enlever de la page concepts
* faire un screen recording de l'ajout d'azimut avec la vue?
* capture d'écran pour le décalage des panneaux
* bouger panneaux directionnels en dehors de la config avancée, faire une page dédiée juste avant (renommern en "signalisation directionnelle"?)
* avec les 2 qui restent: séparer recto-verso et custom en 2 catégories (supprimer "spéciaux")
* sur les conseils, je fais un PR à part
* duplication: video?
* dans env de travail, on parle du plugin pg service parser?
* lien vers la doc DB: ouvrir dans un nouvel onglet?

Joli travail, c'est déjà beaucoup mieux qu'avant!!!

**Comment by itsakifa** [comment]
- [ ] renommer participer en contribuer?
- [ ] harmoniser les titres de chaque page: s'assurer qu'elle commence par le titre et que les sous chapitres suivant aient une police plus petite (la page installation est ok, la page concepts non)
- [ ] la MAJ du modèle de données est présent 2 fois, l'enlever de la page concepts
- [ ] faire un screen recording de l'ajout d'azimut avec la vue?
- [ ] capture d'écran pour le décalage des panneaux
- [ ] bouger panneaux directionnels en dehors de la config avancée, faire une page dédiée juste avant (renommern en "signalisation directionnelle"?)
- [ ] avec les 2 qui restent: séparer recto-verso et custom en 2 catégories (supprimer "spéciaux")
- [ ] sur les conseils, je fais un PR à part
- [ ] duplication: video?
- [ ] dans env de travail, on parle du plugin pg service parser?
- [ ] lien vers la doc DB: ouvrir dans un nouvel onglet?
