### ISSUE TITLE
1.0.0-RC7 - signalo_db : comment effectuer la migration depuis la RC6 ?

### ISSUE THREAD

**Issue by spch-GL** [opengisch/signalo#207]
J'ai fait tourner les 3 nouveaux scripts et ajouté les décalages verso à la main
```
ALTER TABLE signalo_db.azimut ADD COLUMN offset_x_verso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE signalo_db.azimut ADD COLUMN offset_y_verso INTEGER NOT NULL DEFAULT 0;
```
car les noms des scripts du changelog n'avaient pas changé, hormis un numéro d'ordre.

Ainsi la création du schema signalo_app se termine sans erreur et le projet s'ouvre

Mais y a-t-il d'autres corrections à apporter ?

**Comment by 3nids** [comment]
ça m'a lair bon, je fais la même analyse que toi.
Après, c'est une procédure hors sentiers battus, donc sans garantie :)
