### ISSUE TITLE
Documenter la création d'un signal personnalisé 

### ISSUE THREAD

**Issue by spch-GL** [opengisch/signalo#224]
- Création du svg "éditable"
- Mise à jour de la BD

**Comment by itsakifa** [comment]
@spch-GL peux-tu checker si la documentation mise à jour est suffisamment détaillée ?

**Comment by spch-GL** [comment]
@itsakifa il me semble qu'il manque un descriptif pour, si c'est possible :

- l'alignement du texte (gauche, centré et droite) 
- le passage à 2 lignes à la place des 3...

Merci :-)

**Comment by itsakifa** [comment]
@spch-GL - c'est ajouté! J'espère que ça joue comme ça.
