### ISSUE TITLE
Website workflow choking on de_CH

### ISSUE THREAD

**Issue by why-not-try-calmer** [opengisch/signalo#66]
[Transfixed](https://www.transifex.com/opengisch/signalo-website/languages/) lists `de_CH` as a target language but the website workflow has just [failed](https://github.com/opengisch/signalo/actions/runs/3310601779/jobs/5465006452) to build for it. It might be that setting the transifex project to require only `de` (as opposed to `de_CH`) would suffice to fix the issue (other opengisch transifex repos also use `de`). 

(I don't have admin rights for the transifex project)

**Comment by 3nids** [comment]
does it solve the issue: https://github.com/opengisch/signalo/commit/786f7af3403c0623f678d2e2c14cbb0c737c45ef ?

**Comment by why-not-try-calmer** [comment]
> does it solve the issue: [786f7af](https://github.com/opengisch/signalo/commit/786f7af3403c0623f678d2e2c14cbb0c737c45ef) ?

I thought of doing something like that but then I remembered that the search index is quite picky in terms of the languages it accepts to parse / tokenize. So I wanted to avoid the risks.
