### ISSUE TITLE
Missing: captions translation

### ISSUE THREAD

**Issue by why-not-try-calmer** [opengisch/signalo#75]
Courtesy of Isabel we have the translationed captions:
```
Desktop: 
- Reiter Allgemein
- Reiter Azimut
- Reiter Foto
- Beispiel eines Azimuts mit mehreren Rahmen und Signalen
- Einstellung der Bildgrösse
- Filterung der Signale

Mobil:
- Visualisierung in QField
- Editieren der Pfosten
- Editieren des Formulars
```
the problem is how to integrate them. I am not sure how. Usually captions are embeded directly in source files, using a special markup syntax; however translations synced on Transifex don't have any local source files. So the only way seems to write the appropriate markup tags at build time. I don't think we have the technology for this just yet.

**Comment by 3nids** [comment]
fixed
