### ISSUE TITLE
Site_description not translated

### ISSUE THREAD

**Issue by why-not-try-calmer** [opengisch/signalo#78]
`mkdocs.yaml:site_description` is not translated:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/19554213/218775763-30daa4bc-338e-4c51-8196-6eba99643ad2.png">
 
WIP

**Comment by itsakifa** [comment]
@why-not-try-calmer : any news on that?

**Comment by why-not-try-calmer** [comment]
News: https://github.com/squidfunk/mkdocs-material/discussions/5359#discussioncomment-5812615.
Important bit:

> So we're using git+https://github.com/kamilkrzyskow/i18n.git@5e286be68ad6fafed7affd44cd57d3625c0a02cc#egg=mkdocs_static_i18n in the requirements.txt

...to unlock the `site_description` feature.

**Comment by itsakifa** [comment]
Did you test it? @why-not-try-calmer ? :)

**Comment by why-not-try-calmer** [comment]
> Did you test it? @why-not-try-calmer ? :)

Thanks for remining me, I will update here!

**Comment by why-not-try-calmer** [comment]
Okay @itsakifa, you can checkout #110
