### ISSUE TITLE
Issues with recto/verso signs

### ISSUE THREAD

**Issue by 3nids** [opengisch/signalo#83]
Lorsqu'il y a plusieurs panneaux dans le même cadre dont certains en verso, il arrive que la position du verso ne corresponde pas à son recto (je crois que c'est après avoir déplacé un panneau avec le plug-in)

![image](https://user-images.githubusercontent.com/127259/223432073-8295a48f-fa9c-42f5-a33e-b7b9ffb4cd3b.png)

**Comment by spch-GL** [comment]
Lien Click-up pour les images: https://app.clickup.com/t/2192114/DEV-2459

**Comment by spch-GL** [comment]
Autre souci verso décrit (Si l'azimut est différent, il y a aussi la superposition): https://app.clickup.com/t/2192114/DEV-5282

**Comment by spch-GL** [comment]
Avec le projet 041, les signaux recto sont correctement affichés, mais pas les signaux verso qui sont parfois superposés (https://app.clickup.com/t/2192114/DEV-5267)
![image](https://user-images.githubusercontent.com/26377323/223681453-db85fb1b-3756-41fe-ab4b-f78f6e55641f.png)

**Comment by DylanRecordon** [comment]
Bonjour,

Le problème persiste encore, les signaux recto sont correctement affichés, mais pas les signaux verso, sont toujours superposés. Cela rend la saisie pénible. Avez-vous un délai pour la résolution de ce problème ? 

Avec mes meilleures salutations.

**Comment by DylanRecordon** [comment]
Bonjour,

Je me permets d'ajouter un complément pour ces soucis de représentation recto-verso:

- nous avons 4 cadres recto et 1 cadre verso sur un mât:
![image](https://github.com/opengisch/signalo/assets/134506740/f32878e7-5d0d-448a-b0a8-e54ff93474a3)

Voici la représentation dans Signalo:
![image](https://github.com/opengisch/signalo/assets/134506740/6d4e043a-8189-48a9-bca3-df45f51273e5)

Comment faire pour remonter le cadre verso (fin de 60km/h) au niveau de mat?  

Avec mes meilleures salutations
Dylan

**Comment by itsakifa** [comment]
@3nids ça peut être fermé?
