### ISSUE TITLE
Unstable display - Signalo 0.5.2 with QGIS 3.30.0

### ISSUE THREAD

**Issue by gildas-allaz** [opengisch/signalo#99]
Bonjour,

La dernière version de Signalo, 0.5.2 du 08.05.2023, utilisée avec les versions 3.30.0 (tel que livré par OPENGIS) ou 3.30.3 de QGIS, présente une instabilité d'affichage.

Lors de la sélection d'un signal dans le formulaire attributaire, une fenêtre "fantôme" s'ouvre par-dessus le formulaire et en empêche l'utilisation et un masque noir remplace les svg des signaux :
![image](https://github.com/opengisch/signalo/assets/70746346/f2ce0f39-7b93-4e89-950b-4aae4f42208f)

Ce bug n'apparait pas dans les versions LTR de QGIS (3.28.4, 3.28.7). Cependant, l'ouverture du projet qgs Signalo 0.5.2 avec une version LTR antérieur à 3.30.0 affiche la mention : Ce fichier de projet a été créé par une version plus récente de QGIS (3.30.0-'s-Hertogenbosch) et n'a pas pu être complètement chargé.

Pourriez-vous soit :
•	résoudre le bug d'affichage
•	communiquer quels sont les problèmes et risques encourus lors de l'ouverture du projet qgs Signalo 0.5.2 avec une version LTR antérieur à 3.30.0

Avec mes cordiales salutations.

Gildas Allaz

**Comment by 3nids** [comment]
Comment a été installé QGIS? Est-ce avec l'installeur OSGEO4W ou l'installeur standalone?

**Comment by gildas-allaz** [comment]
Lors de mon test du 19.06.2023, j'ai utilisé une version avec installation standalone.
(car difficulté à contourner les sécurités informatiques).

Aujourd'hui, installation OSGEO4W avec installateur téléchargé du jour sur site QGIS, mais problème d'affichage identique avec :
- QGIS 3.30.3
- Signalo 0.6.0

A disposition pour contact téléphonique ou vidéoconférence pour plus de détails
